# Generated by Django 6.1.1 on 2026-09-22 18:16

import core.encrypt
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ya_id', models.CharField(max_length=255, unique=True, verbose_name='идентификатор Я ID')),
                ('access_token', core.encrypt.EncryptedTextField(blank=True, null=True, verbose_name='OAuth access token Я ID')),
                ('refresh_token', core.encrypt.EncryptedTextField(blank=True, null=True, verbose_name='OAuth refresh token Я ID')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='срок access token')),
                ('sourcecraft_pat', core.encrypt.EncryptedTextField(blank=True, help_text='Нужен, если токен Я ID не подходит для API SourceCraft', null=True, verbose_name='персональный токен SourceCraft')),
                ('sourcecraft_username', models.CharField(blank=True, max_length=255, verbose_name='логин SourceCraft')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_slug', models.CharField(max_length=255, verbose_name='организация')),
                ('repo_slug', models.CharField(max_length=500, verbose_name='репозиторий')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('language', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='язык')),
                ('rating_value', models.FloatField(default=0, help_text='rating.value — составной рейтинг платформы, им сортируем', verbose_name='рейтинг SourceCraft')),
                ('rating_percentile', models.FloatField(blank=True, help_text='1 = топ-1% публичных репозиториев SourceCraft', null=True, verbose_name='перцентиль рейтинга')),
                ('likes', models.PositiveIntegerField(default=0, help_text='👍 positive_low', verbose_name='лайки')),
                ('hearts', models.PositiveIntegerField(default=0, help_text='❤️ positive_medium', verbose_name='сердца')),
                ('diamonds', models.PositiveIntegerField(default=0, help_text='💎 positive_high', verbose_name='бриллианты')),
                ('health_score', models.PositiveSmallIntegerField(blank=True, help_text='Кэш итогового Score 0–100, null = ещё не считали', null=True, verbose_name='Repo Health Score')),
                ('forks', models.PositiveIntegerField(default=0, verbose_name='форки')),
                ('sourcecraft_id', models.CharField(max_length=255, unique=True, verbose_name='идентификатор SourceCraft')),
                ('url', models.URLField(max_length=500)),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('is_empty', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('internal', 'internal'), ('private', 'private')], db_index=True, max_length=10)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя проверка')),
                ('last_commit_sha_processed', models.CharField(blank=True, max_length=64, verbose_name='поледний просканированный хеш коммита')),
                ('default_branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='ветка по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'репозиторий',
                'verbose_name_plural': 'репозитории',
                'ordering': ['org_slug', 'repo_slug'],
                'indexes': [models.Index(fields=['visibility', '-rating_value'], name='health_repo_visibil_rating_idx'), models.Index(fields=['visibility', '-health_score'], name='health_repo_visibil_score_idx'), models.Index(fields=['visibility', 'language'], name='health_repo_visibil_lang_idx')],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'в очереди'), ('running', 'идёт'), ('success', 'готово'), ('failed', 'ошибка'), ('partial', 'частично (часть данных недоступна)')], default='pending', max_length=10, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершён')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='сырые данные')),
                ('error', models.TextField(blank=True, null=True, verbose_name='ошибка')),
                ('triggered_by', models.CharField(choices=[('schedule', 'по расписанию'), ('user', 'пользователем'), ('manual', 'вручную (management-команда)')], max_length=20, verbose_name='кем запущен')),
                ('commit_sha_at_analysis', models.CharField(blank=True, max_length=64, null=True, verbose_name='хеш коммита')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='health.repository', verbose_name='репозиторий')),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'проверка',
                'verbose_name_plural': 'проверки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('docs', 'документация и лучшие практики'), ('ci_cd', 'CI/CD'), ('security', 'security'), ('activity', 'активность проекта'), ('issues', 'issues'), ('code_health', 'состояние кода и технический долг')], max_length=15, verbose_name='категория')),
                ('metric_key', models.CharField(max_length=100, verbose_name='например: ci_success_rate_90d, readme_present, todo_count')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='значение метрики (число/строка/структура) или null, если недоступно')),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('is_available', models.BooleanField(default=True, help_text="False = данные недоступны ('нет данных'), не путать со значением 0", verbose_name='доступность')),
                ('error_reason', models.CharField(blank=True, max_length=255, verbose_name='причина недоступности, если is_available=False')),
                ('source_reference', models.CharField(blank=True, max_length=500, verbose_name='ссылка на файл/pipeline/commit/issue/MR, подтверждающая метрику')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to='health.scan')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
            },
        ),
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('docs', 'документация и лучшие практики'), ('ci_cd', 'CI/CD'), ('security', 'security'), ('activity', 'активность проекта'), ('issues', 'issues'), ('code_health', 'состояние кода и технический долг')], max_length=15, verbose_name='категория')),
                ('total', models.PositiveSmallIntegerField(blank=True, help_text="0-100, null = категория помечена 'Нет данных'", null=True, verbose_name='итого')),
                ('weight_used', models.FloatField(verbose_name='вес категории, фактически применённый при расчёте (после перенормировки)')),
                ('data_completeness', models.FloatField(default=1.0, verbose_name='доля доступных метрик категории, от 0.0 до 1.0')),
                ('raw_metrics', models.JSONField(blank=True, default=dict, verbose_name='снимок значений метрик, использованных в расчёте')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='health.scan', verbose_name='проверка')),
            ],
            options={
                'verbose_name': 'оценка по категории',
                'verbose_name_plural': 'оценки по категории',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('docs', 'документация и лучшие практики'), ('ci_cd', 'CI/CD'), ('security', 'security'), ('activity', 'активность проекта'), ('issues', 'issues'), ('code_health', 'состояние кода и технический долг')], max_length=15, verbose_name='категория')),
                ('severity', models.CharField(choices=[('1', 'low'), ('2', 'medium'), ('3', 'high'), ('4', 'critical')], max_length=16, verbose_name='серьёзность')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('detail', models.TextField(blank=True, verbose_name='детали')),
                ('recommendation', models.TextField(blank=True, verbose_name='рекомендация')),
                ('evidence_refs', models.JSONField(blank=True, default=list, verbose_name='список ссылок на факты: файлы/pipeline/vulnerability/commit/issue/MR')),
                ('estimated_score_impact', models.SmallIntegerField(default=0, verbose_name='ожидаемый прирост Repo Health Score при устранении проблемы')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='health.scan', verbose_name='проверка')),
            ],
            options={
                'verbose_name': 'находка',
                'verbose_name_plural': 'находки',
                'ordering': ['-estimated_score_impact', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='UserRepositoryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='health.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'доступ к репозиторию',
                'verbose_name_plural': 'доступ к репозиториям',
            },
        ),
        migrations.AddConstraint(
            model_name='scan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('repository',), name='one_active_scan_per_repo'),
        ),
        migrations.AlterUniqueTogether(
            name='metricsample',
            unique_together={('scan', 'category', 'metric_key')},
        ),
        migrations.AlterUniqueTogether(
            name='healthscore',
            unique_together={('scan', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='userrepositoryaccess',
            unique_together={('user', 'repository')},
        ),
    ]
