# Generated by Django 6.1.1 on 2026-09-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='issues',
            field=models.PositiveIntegerField(default=0, verbose_name='issues'),
        ),
    ]
