# Generated by Django 6.1.1 on 2026-09-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_scan_checking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='category',
            field=models.CharField(choices=[('docs', 'Документация'), ('ci_cd', 'CI/CD'), ('security', 'Безопасность'), ('activity', 'Активность'), ('issues', 'Issues'), ('code_health', 'Состояние кода')], max_length=15, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('1', 'низкая'), ('2', 'средняя'), ('3', 'высокая'), ('4', 'критическая')], max_length=16, verbose_name='серьёзность'),
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='category',
            field=models.CharField(choices=[('docs', 'Документация'), ('ci_cd', 'CI/CD'), ('security', 'Безопасность'), ('activity', 'Активность'), ('issues', 'Issues'), ('code_health', 'Состояние кода')], max_length=15, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='metricsample',
            name='category',
            field=models.CharField(choices=[('docs', 'Документация'), ('ci_cd', 'CI/CD'), ('security', 'Безопасность'), ('activity', 'Активность'), ('issues', 'Issues'), ('code_health', 'Состояние кода')], max_length=15, verbose_name='категория'),
        ),
    ]
